announce = false
debug = true
description = 'test'
gamemode = 'Freeroam'
host = '0.0.0.0'
language = 'en'
modules = [ 'js-module' ]
name = 'FREEROAM Project @ 1.0.1'
password = 'aASJDijLALKSjli'
players = 1024
port = 7788
resources = [ 'freeroam' ]
tags = [  ]
website = 'freero.am'