announce = false

description = 'test'
website = 'https://freero.am'
gamemode = 'Freeroam'

language = 'en'
modules = [ 'js-module' ]
name = 'freero.am @ play for fun'
players = 1024
port = 7788
tags = [ 'freero.am', 'dm', 'dethmatch' ]

resources = [
    'core',
    'dbg_reconnect'
]

# Turn this off in production mode
debug = true

# Leave host as 0.0.0.0, don't change it.
host = '0.0.0.0'

[js-module]
global-webcrypto = true
global-fetch = true

[voice]
bitrate = 64000
